name: new_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - attrs=25.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter=1.1.1
  - jupyter_client=7.3.4
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_server=1.24.0
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.1
  - nbclassic=1.2.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - openssl=3.0.15
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python_abi=3.10
  - pytz=2025.1
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rpds-py=0.22.3
  - send2trash=1.8.3
  - setuptools=75.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
    - annotated-types==0.7.0
    - blis==1.2.0
    - catalogue==2.0.10
    - click==8.1.8
    - cloudpathlib==0.20.0
    - confection==0.1.5
    - cymem==2.0.11
    - en-core-web-sm==3.8.0
    - langcodes==3.5.0
    - language-data==1.3.0
    - marisa-trie==1.2.1
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - murmurhash==1.0.12
    - numpy==2.2.3
    - pandas==2.2.3
    - preshed==3.0.9
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - rich==13.9.4
    - shellingham==1.5.4
    - smart-open==7.1.0
    - spacy==3.8.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.5.1
    - tbb==2022.0.0
    - tcmlib==1.2.0
    - thinc==8.3.4
    - tqdm==4.67.1
    - typer==0.15.1
    - tzdata==2025.2
    - urllib3==2.3.0
    - wasabi==1.1.3
    - weasel==0.4.1
    - wrapt==1.17.2
